ext {
    //region Android
    androidX = [
            //https://developer.android.com/jetpack/androidx/releases/core
            coreKtx  : 'androidx.core:core-ktx:1.13.1',
            //https://developer.android.com/jetpack/androidx/releases/appcompat
            appCompat: 'androidx.appcompat:appcompat:1.7.0',
            test     : [
                    //https://androidx.tech/artifacts/test.ext/junit/
                    androidJUnit: "androidx.test.ext:junit:1.2.1",
                    //https://androidx.tech/artifacts/test.espresso/espresso-core/
                    espresso    : 'androidx.test.espresso:espresso-core:3.6.1'
            ]
    ]
    //endregion

    //region Kotlin
    //https://github.com/JetBrains/kotlin
    kotlin_version = "2.0.20"
    //https://github.com/Kotlin/kotlinx.coroutines
    coroutines_version = "1.9.0-RC.2"
    //https://github.com/Kotlin/kotlinx.serialization
    kotlinx_serialization_version = "1.7.2"
    kotlin = [
            coroutinesAndroid: [
                    coroutinesAndroid    : "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_version",
                    coroutinesAndroidTest: "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines_version"
            ],
            serialization    : [
                    json: "org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinx_serialization_version",
            ]
    ]
    //endregion

    //https://github.com/trifork/TIMEncryptedStorage-Android
    tim_encrypted_storage_version = "2.1.1"

    timEncryptedStorage = "com.github.trifork:TIMEncryptedStorage-Android:$tim_encrypted_storage_version"

    //https://github.com/openid/AppAuth-Android
    appauth_version = "0.11.1"
    appAuth = "net.openid:appauth:$appauth_version"

    // Instrumented test is not yet supported in jUnit5? Therefore we still use 4
    //https://github.com/junit-team/junit4
    jUnit4_version = "4.13.2"
    jUnit = [
            junit: "junit:junit:$jUnit4_version",

    ]

    //https://search.maven.org/search?q=a:mockk
    mockk_version = "1.13.12"
    mockk = [
            mockk  : "io.mockk:mockk:$mockk_version",
            android: "io.mockk:mockk-android:$mockk_version",
            jvm    : "io.mockk:mockk-agent-jvm:$mockk_version"
    ]

    biometric_version = "1.2.0-alpha05"
    biometric = [
            //https://developer.android.com/jetpack/androidx/releases/biometric
            biometric: "androidx.biometric:biometric-ktx:$biometric_version"
    ]

    //https://github.com/robolectric/robolectric
    roboleltric_version = "4.13"
    roboleltric = [
            roboleltric: "org.robolectric:robolectric:$roboleltric_version"
    ]

    //https://developer.android.com/jetpack/androidx/releases/lifecycle
    androidx_lifecycle_version = "2.8.5"
    lifecycle = [
            commonJava8: "androidx.lifecycle:lifecycle-common-java8:$androidx_lifecycle_version",
            androidx   : "androidx.lifecycle:lifecycle-process:$androidx_lifecycle_version"
    ]
    desugar_jdk_libs_version = "2.1.2"
    desugar_jdk_libs = "com.android.tools:desugar_jdk_libs:$desugar_jdk_libs_version"
}